<h2>Movie Reviews</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import nltk

In [2]:
# Importing the dataset 
from nltk.corpus import movie_reviews

In [3]:
print(movie_reviews.categories())

['neg', 'pos']


In [4]:
neg_rev = movie_reviews.fileids('neg')
len(neg_rev)
# Have 1000 Negetively Clsddified Reviews Traing Data

1000

In [5]:
print(neg_rev[3])

neg/cv003_12683.txt


In [6]:
rev_list = []
for rev in neg_rev:
    rev_text_neg = rev = nltk.corpus.movie_reviews.words(rev)
    review_one_string = " ".join(rev_text_neg)
    review_one_string = review_one_string.replace(" ,",",")
    review_one_string = review_one_string.replace(" .",".")
    review_one_string = review_one_string.replace("\' ","'")
    review_one_string = review_one_string.replace(" \' ","'")
    rev_list.append(review_one_string)

In [7]:
 len(rev_list)

1000

In [8]:
pos_rev = movie_reviews.fileids('pos')

In [9]:

for rev_pos in pos_rev:
    rev_text_neg = rev = nltk.corpus.movie_reviews.words(rev_pos)
    review_one_string = " ".join(rev_text_neg)
    review_one_string = review_one_string.replace(" ,",",")
    review_one_string = review_one_string.replace(" .",".")
    review_one_string = review_one_string.replace("\' ","'")
    review_one_string = review_one_string.replace(" \' ","'")
    rev_list.append(review_one_string)

In [10]:
len(rev_list)

2000

In [11]:
# Creationg A Target List
#Wheae Positive == 1 negative == 0
neg_target = np.zeros((1000,),dtype=np.int)
pos_target = np.ones((1000,),dtype=np.int)

In [12]:

target_list = []
for neg_tar in neg_target:
    target_list.append(neg_tar)
    
for pos_tar in pos_target:
    target_list.append(pos_tar)

In [13]:
len(target_list)

2000

In [41]:
rev_list[170]

'mulholland drive did very well at the cannes film festival. as you can see from the rating it did not do very well from me at the toronto international film festival. it may not be clear to the viewer why i am so negative on this film for most of the running time. in fact it is an interesting mystery story told on the backdrop of the hollywood film industry. toward the end of the film i think everything that has been built falls apart. the film was to be a pilot for a tv series but writer and director david lynch did not sell his tv pilot and i think he decided that he wanted to do something else with it. something else is what he did. the film opens with a woman ( played by laura harring ) about to be killed in a car when a car crash saves her life. she crawls away from the accident with a concussion and finds herself a bungalow with an unlocked door to sleep. meanwhile young vivacious betty ( naomi watts ) arrives in hollywood from canada. she wants to build a career as an actress. 

In [35]:
# Creating Pandas Seris
y = pd.Series(target_list)
type(y)

pandas.core.series.Series

In [36]:
count_vect = CountVectorizer(lowercase=True,stop_words='english',min_df=2)

In [37]:
#Turning the Revirw list to vecter Form
X_count_vect = count_vect.fit_transform(rev_list)


In [38]:
X_count_vect.shape

(2000, 23784)

In [39]:
#  Craeting the Freature Names Library
X_names = count_vect.get_feature_names()


In [40]:
# Creating a Pandas Data Frame
X_count_vect = pd.DataFrame(X_count_vect.toarray(), columns=X_names)

In [41]:
X_count_vect.shape

(2000, 23784)

In [49]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_pca)
x_pca = scaler.transform(x_pca)

In [46]:
x_pca

array([[-1.41529048e+00,  6.78656701e-01,  4.24970004e-01, ...,
         1.24274685e-18,  1.01012384e-18,  9.57661828e-19],
       [-6.07280497e+00,  5.01315945e+00,  7.17722596e-01, ...,
         1.24274685e-18,  1.01012384e-18,  9.57661828e-19],
       [-2.62632031e+00,  2.40924904e+00,  1.97484377e-01, ...,
         1.24274685e-18,  1.01012384e-18,  9.57661828e-19],
       ...,
       [ 8.40671581e+00, -1.00808075e+01, -3.59652195e+00, ...,
         1.24274685e-18,  1.01012384e-18,  9.57661828e-19],
       [-1.31851576e+00,  1.55501489e+00,  3.60738539e-02, ...,
         1.24274685e-18,  1.01012384e-18,  9.57661828e-19],
       [ 3.51701746e+00, -3.95628327e+00, -6.82108387e-01, ...,
         1.24274685e-18,  1.01012384e-18,  9.57661828e-19]])

In [50]:
# Spliting to Tranning And Tet Sets
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
X_train_pca,X_test_pca,y_train_pca,y_test_pca = train_test_split(x_pca,y,test_size= 0.2, random_state = 5)

In [52]:
X_train_pca

array([[-4.87560694e-01,  4.14582679e-01,  1.60600475e-01, ...,
         3.76977386e-16, -1.12806926e-15,  1.87222442e-15],
       [-4.46809913e-01,  4.55229866e-01, -2.41952722e-02, ...,
         3.45434380e-16,  2.56137643e-16, -1.27360913e-15],
       [-5.94117377e-01,  5.00441084e-01,  1.74623497e-01, ...,
         2.12338283e-16,  1.84169273e-15, -2.80485336e-15],
       ...,
       [-3.69505226e-01,  2.86666361e-01,  4.72906252e-02, ...,
        -1.88986201e-15, -1.61684568e-15,  1.45549900e-15],
       [-4.25542093e-01,  2.86913528e-01, -3.55461513e-02, ...,
        -4.63656540e-17, -4.32255461e-16,  2.86679218e-15],
       [-3.00134574e-02, -2.41131537e-01, -2.68635173e-01, ...,
         6.52504260e-16,  3.82165773e-16, -7.61252198e-17]])

In [51]:
from sklearn.naive_bayes import MultinomialNB
clf_cv = MultinomialNB()
clf_cv.fit(X_train_pca,y_train_pca)
y_pred = clf_cv.predict(X_test_pca)
print (metrics.accuracy_score(y_test_pca,y_pred))

ValueError: Input X must be non-negative

In [26]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2)
kmeans.fit(x_pca)

np.mean(kmeans.labels_ == y)


0.535

In [49]:
# Spliting to Tranning And Tet Sets
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
X_train,X_test,y_train,y_test = train_test_split(X_count_vect,y,test_size= 0.2, random_state = 5)

In [50]:
X_train.shape

(1600, 23784)

<h2>Naive Bays</h2>

In [51]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train,y_train).predict(X_test)

from sklearn.naive_bayes import MultinomialNB


In [52]:
clf_cv = MultinomialNB()
clf_cv.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [53]:
y_pred = clf_cv.predict(X_test)
type(y_pred)

numpy.ndarray

In [54]:
# Accuracy
print (metrics.accuracy_score(y_test,y_pred))

0.8225


In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[181,  30],
       [ 41, 148]], dtype=int64)

In [55]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       211
           1       0.83      0.78      0.81       189

   micro avg       0.82      0.82      0.82       400
   macro avg       0.82      0.82      0.82       400
weighted avg       0.82      0.82      0.82       400



<h2>Support Vecter Machine </h2>

In [56]:
from sklearn.linear_model import SGDClassifier
SVMcls = SGDClassifier()
y_pred = SVMcls.fit(X_train,y_train).predict(X_test)

# Accuracy
print (metrics.accuracy_score(y_test,y_pred))



C:\Users\smvdi\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.8275


In [58]:
cm2 = confusion_matrix(y_test,y_pred)
cm2

array([[169,  42],
       [ 27, 162]], dtype=int64)

In [59]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.80      0.83       211
           1       0.79      0.86      0.82       189

   micro avg       0.83      0.83      0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400



<h2>Logistic Regression </h2>

In [60]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
y_pred = logreg.fit(X_train,y_train).predict(X_test)



C:\Users\smvdi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [61]:
print (metrics.accuracy_score(y_test,y_pred))

0.875


In [62]:
cm3 = confusion_matrix(y_test,y_pred)
cm3

array([[187,  24],
       [ 26, 163]], dtype=int64)

In [63]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.89      0.88       211
           1       0.87      0.86      0.87       189

   micro avg       0.88      0.88      0.88       400
   macro avg       0.87      0.87      0.87       400
weighted avg       0.87      0.88      0.87       400



In [64]:
from sklearn.ensemble import RandomForestClassifier

random = RandomForestClassifier(n_estimators=75,random_state=0,criterion='entropy')
y_pred = random.fit(X_train,y_train).predict(X_test)
print (metrics.accuracy_score(y_test,y_pred))



0.835


In [65]:
cm4 = confusion_matrix(y_test,y_pred)
cm4

array([[167,  44],
       [ 22, 167]], dtype=int64)

In [66]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.79      0.84       211
           1       0.79      0.88      0.84       189

   micro avg       0.83      0.83      0.83       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.83      0.83       400



In [67]:
from sklearn.tree import DecisionTreeClassifier

distree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
y_pred = distree.fit(X_train,y_train).predict(X_test)
print (metrics.accuracy_score(y_test,y_pred))



0.6325


In [68]:

cm5 = confusion_matrix(y_test,y_pred)
cm5

array([[131,  80],
       [ 67, 122]], dtype=int64)

In [69]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.62      0.64       211
           1       0.60      0.65      0.62       189

   micro avg       0.63      0.63      0.63       400
   macro avg       0.63      0.63      0.63       400
weighted avg       0.63      0.63      0.63       400

